INSERT INTO TBL_PRODUCT(NAME) VALUES ('Product 1');
INSERT INTO TBL_PRODUCT(NAME) VALUES ('Product 2');
INSERT INTO TBL_PRODUCT(NAME) VALUES ('Product 3');
INSERT INTO TBL_PRODUCT(NAME) VALUES ('Product 4');
INSERT INTO TBL_PRODUCT(NAME) VALUES ('Product 5');
