INSERT INTO TBL_PRODUCT(NAME) VALUES ('Test Product');
INSERT INTO TBL_ORDER(ORDER_DATE) VALUES ('2020-01-01');
INSERT INTO TBL_SALES(SALES_DATE) VALUES ('2020-01-01');
INSERT INTO TBL_ORDERITEM(ORDER_NUMBER, PRODUCT_ID, QUANTITY, PRICE) VALUES ((SELECT ORDER_NUMBER FROM TBL_ORDER LIMIT 1), (SELECT PRODUCT_ID FROM TBL_PRODUCT LIMIT 1), 1, 1.00);
INSERT INTO TBL_ORDERITEM(ORDER_NUMBER, PRODUCT_ID, QUANTITY, PRICE) VALUES ((SELECT ORDER_NUMBER FROM TBL_ORDER LIMIT 1), (SELECT PRODUCT_ID FROM TBL_PRODUCT LIMIT 1), 1, 2.00);
INSERT INTO TBL_SALE(SALES_ID, PRODUCT_ID, TOTAL_QTY, TOTAL_AMOUNT) VALUES ((SELECT SALES_ID FROM TBL_SALES LIMIT 1), (SELECT PRODUCT_ID FROM TBL_PRODUCT LIMIT 1), 1, 1.00);