CREATE TABLE TBL_ORDER(
  ORDER_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
  ORDER_DATE DATE
);

CREATE TABLE TBL_ORDERITEM(
  ORDERITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ORDER_NUMBER BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY INT NOT NULL,
  PRICE DECIMAL NOT NULL
);

CREATE TABLE TBL_PRODUCT(
  PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(24) UNIQUE NOT NULL
);

CREATE TABLE TBL_SALES(
  SALES_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SALES_DATE DATE
);

CREATE TABLE TBL_SALE(
  SALE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  SALES_ID BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  TOTAL_QTY INT NOT NULL,
  TOTAL_AMOUNT DECIMAL NOT NULL
);

ALTER TABLE TBL_ORDERITEM ADD FOREIGN KEY (ORDER_NUMBER) REFERENCES TBL_ORDER(ORDER_NUMBER);
ALTER TABLE TBL_ORDERITEM ADD FOREIGN KEY (PRODUCT_ID) REFERENCES TBL_PRODUCT(PRODUCT_ID);
ALTER TABLE TBL_SALE ADD FOREIGN KEY (SALES_ID) REFERENCES TBL_SALES(SALES_ID);
ALTER TABLE TBL_SALE ADD FOREIGN KEY (PRODUCT_ID) REFERENCES TBL_PRODUCT(PRODUCT_ID);
CREATE INDEX IDX_SALES_DATE_ ON TBL_SALES(SALES_DATE);
