CREATE TABLE TBL_ORDER(
  ORDER_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
  ORDER_DATE DATE
);

CREATE TABLE TBL_ORDERITEM(
  ORDERITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ORDER_NUMBER BIGINT NOT NULL,
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY INT NOT NULL,
  PRICE DECIMAL NOT NULL
);

CREATE TABLE TBL_PRODUCT(
  PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(24) UNIQUE NOT NULL
);


ALTER TABLE TBL_ORDERITEM ADD FOREIGN KEY (PRODUCT_ID) REFERENCES TBL_PRODUCT(PRODUCT_ID);
CREATE INDEX IDX_ORDER_DATE ON TBL_ORDER(ORDER_DATE);
CREATE SEQUENCE ORDER_SEQUENCE_ID START WITH (select max(ORDER_NUMBER) + 1 from TBL_ORDER);
CREATE SEQUENCE ORDERITEM_SEQUENCE_ID START WITH (select max(ORDERITEM_ID) + 1 from TBL_ORDERITEM);
